name: Publish maven package on github maven repo

on:
  release:
    types: [created]
    
jobs:
  remove-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove SNAPSHOT from pom.xml
        run: mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.io"
          git config --global user.name "github-actions"
          git commit -am "Remove SNAPSHOT from pom.xml"
          git push

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_REPO_GITHUB_TOKEN }}